FROM node:12

RUN apt-get update
RUN apt-get install -y libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0
RUN echo "build app: $APP"
WORKDIR /app
COPY backend/package.json ./package.json
COPY backend/package-lock.json ./package-lock.json
COPY backend/build/backend/src ./
RUN npm i --only=production
RUN ls -a .
CMD ["node","server.js"]
